name: Terraform Workflow
on:
  pull_request:
    branches: [main]
    paths:
      - "terraform/**"
  push:
    branches: [main]
    paths:
      - "terraform/**"
permissions:
  id-token: write
  contents: read
jobs:
  merge_flow:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCT_ID }}:role/github-actions-role
          role-session-name: gha-session
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -out=tfplan

      - name: Upload Plan
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: tf-plan
          path: terraform/tfplan
          retention-days: 5

      - name: Download Plan
        if: github.event_name == 'push'
        uses: actions/download-artifact@v3
        with:
          name: tf-plan
          path: terraform/tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan