name: Merge Workflow
on:
  push:
    branches: [main]
    paths:
      - "terraform/**"
permissions:
  id-token: write
  contents: read
jobs:
  merge_flow:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCT_ID }}:role/github-actions-role
          role-session-name: gha-session
          aws-region: eu-west-1

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tf-plan
          # path: terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
